"""описание

Revision ID: 5c5b70a75f42
Revises: a3b980885df8
Create Date: 2025-05-29 08:42:24.071693

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5c5b70a75f42"
down_revision: str | None = "a3b980885df8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
